services:
  resourcespace:
    build: .
    container_name: resourcespace
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - db.env
    user: '0:33' # Root and www-data group, non root will be assigned later
    volumes:
      - filestore:/var/www/html/filestore
      - ./config.php:/tmp/config.php
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache2.conf:/etc/apache2/apache2.conf
    networks:
      - frontend
      - backend
    ports:
      - '80:80'

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mariadb:
  filestore:
