services:
  resourcespace:
    build: .
    container_name: resourcespace
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file:
      - db.env
    environment:
      - RESOURCESPACE_HOST=${RESOURCESPACE_HOST:-}
    user: '0:33' # Root and www-data group, non root will be assigned later
    volumes:
      - filestore:/var/www/html/filestore
      - ./config.php:/var/www/html/include/config.php
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache2.conf:/etc/apache2/apache2.conf
      - ./helperScript/rs_helper.php:/var/www/html/rs_helper/index.php
    networks:
      - frontend
      - backend
    ports:
      - '8000:80'

  mariadb:
    image: mariadb:12.3.1-ubi10-rc@sha256:91cb55e4889475692e096d337a93a11a7dd31c30251e2bbd91766f070e638a80
    container_name: mariadb_resourcespace
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mariadb:
  filestore:
